-- %TYPE -- %ROWTYPE
-- Senaryo : DEPARTMENTS Tablosundan, DEPARTMENT_ID'si 10 olan kaydý ekrana listeleyelim.

DECLARE
    --WDEPARTMENT_ID     NUMBER(4);    
    --WDEPARTMENT_NAME   VARCHAR2(30);
    --WMANAGER_ID        NUMBER(6);   
    --WLOCATION_ID       NUMBER(4);
    
    --Tablo üzerinde sonradan degisme ihtimali icin(Uzunluklarýn):
    WDEPARTMENT_ID     DEPARTMENTS.DEPARTMENT_ID%TYPE;    
    WDEPARTMENT_NAME   DEPARTMENTS.DEPARTMENT_NAME%TYPE; 
    WMANAGER_ID        DEPARTMENTS.MANAGER_ID%TYPE;    
    WLOCATION_ID       DEPARTMENTS.LOCATION_ID%TYPE; 
    
BEGIN
    
    SELECT * INTO WDEPARTMENT_ID, WDEPARTMENT_NAME, WMANAGER_ID , WLOCATION_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = 10;
    
    DBMS_OUTPUT.PUT_LINE(WDEPARTMENT_ID||' '|| WDEPARTMENT_NAME||' '|| WMANAGER_ID||' '|| WLOCATION_ID);
    
END;